name: vibe
description: "A next gen music app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  supabase_flutter: ^2.12.4
  flutter_dotenv: ^6.0.1
  flutter_riverpod: ^3.3.1
  http: ^1.6.0
  riverpod_annotation: ^4.0.2
  awesome_snackbar_content: ^0.1.8
  palette_generator_master: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.3
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true

  assets:
    - lib/core/images/
    - lib/core/fonts/
    - .env

  fonts:
    - family: SF Pro
      fonts:
        - asset: lib/core/fonts/sf_pro/SFPRODISPLAYREGULAR.otf
        - asset: lib/core/fonts/sf_pro/SFPRODISPLAYMEDIUM.otf
        - asset: lib/core/fonts/sf_pro/SFPRODISPLAYBOLD.otf